-- 
-- Contenu de la table `indexint`
-- 

INSERT INTO indexint VALUES (1, '0', 'Generalidades. Informação. Organização ', ' 0 generalidades informacao organizacao ');
INSERT INTO indexint VALUES (2, '01', 'Bibliografias. Catálogos ', ' 01 bibliografias catalogos ');
INSERT INTO indexint VALUES (3, '02', 'Bibliotecas. Biblioteconomia ', ' 02 bibliotecas biblioteconomia ');
INSERT INTO indexint VALUES (4, '030',  'Ensaios, Panfletos, e Brochuras ', ' 030 ensaios panfletos e brochuras ');
INSERT INTO indexint VALUES (5, '040',  'Publicações Periódicas. Periódicos  ', ' 040 publicacoes periodicas periodicos  ');
INSERT INTO indexint VALUES (6, '050', 'Publicações Periódicas. Periódicos ', ' 050 publicacoes periodicas periodicos ');
INSERT INTO indexint VALUES (7, '06', 'Instituições. Academias. Congressos. Sociedades. Organismos Científicos. Exposições. Museus ', '06 instituicoes academias congressos sociedades organismos cientificos exposicoes museus ');
INSERT INTO indexint VALUES (8, '070', 'Jornais. Jornalismo. Imprensa ', ' 070 jornais jornalismo imprensa ');
INSERT INTO indexint VALUES (9, '08', 'Poligrafias. Poligrafias Colectivas ', ' 08 poligrafias poligrafias colectivas ');
INSERT INTO indexint VALUES (10, '09', 'Manuscritos. Obras Notáveis e Obras Raras ', ' 09 manuscritos obras notaveis e obras raras ');
INSERT INTO indexint VALUES (11, '1', 'Filosofia. Psicologia ', ' 1 filosofia psicologia ');
INSERT INTO indexint VALUES (12, '11', 'Metafísica ', ' 11 metafisica ');
INSERT INTO indexint VALUES (13, '133', 'Metafísica da vida espiritual. Ocultismo ', ' 133 metafisica da vida espiritual ocultismo ');
INSERT INTO indexint VALUES (14, '14', 'Sistemas e pontos de vista filosóficos ', ' 14 sistemas e pontos de vista filosoficos ');
INSERT INTO indexint VALUES (15, '159.1', 'Psicologia ', ' 1591 psicologia ');
INSERT INTO indexint VALUES (16, '16', 'Lógica. Teoria do Conhecimento. Metodologia da Lógica ', ' 16 logica teoria do conhecimento metodologia da logica ');
INSERT INTO indexint VALUES (17, '17', 'Filosofia Moral. Ética. Filosofia Prática ', ' 17 filosofia moral etica filosofia pratica ');
INSERT INTO indexint VALUES (18, '2', 'Religião. Teologia ', ' 2 religiao teologia ');
INSERT INTO indexint VALUES (19, '21', Teologia Natural. Teologia Racional. Filosofia Religiosa ', ' 21 teologia natural teologia racional filosofia religiosa  ');
INSERT INTO indexint VALUES (20, '22', 'A Bíblia. Sagradas Escrituras ', ' 22 a biblia sagradas escrituras ');
INSERT INTO indexint VALUES (21, '23', 'Teologia Dogmática ', ' 23 teologia dogmatica ');
INSERT INTO indexint VALUES (22, '24', 'Teologia Prática ', ' 24 teologia pratica ');
INSERT INTO indexint VALUES (23, '25', 'Teologia Pastoral ', ' 25 teologia pastoral ');
INSERT INTO indexint VALUES (24, '26', 'Igreja Cristã em Geral ', ' 26 igreja crista em geral ');
INSERT INTO indexint VALUES (25, '27', 'História Geral da Igreja Cristã ', ' 27 historia geral da igreja crista ');
INSERT INTO indexint VALUES (26, '28', 'Igrejas Cristãs. Seitas. Denominações (Confissões) ', ' 28 igrejas cristas seitas denominacoes confissoes ');
INSERT INTO indexint VALUES (27, '29', 'Religiões não cristãs ', ' 29 religioes nao cristas ');
INSERT INTO indexint VALUES (28, '3', 'Ciências Sociais. Economia. Direito. Política. Assistência Social. Educação ', ' 3 ciencias sociais economia direito politica assistencia social educacao ');
INSERT INTO indexint VALUES (29, '31', 'Demografia. Sociologia. Estatística ', ' 31 demografia sociologia estatistica ');
INSERT INTO indexint VALUES (30, '32', 'Política ', ' 32 politica ');
INSERT INTO indexint VALUES (31, '33', 'Economia. Ciência Económica ', ' 33 economia ciencia economica ');
INSERT INTO indexint VALUES (32, '34', 'Direito. Jurisprudência ', ' 34 direito jurisprudencia ');
INSERT INTO indexint VALUES (33, '35', 'Administração Pública. Governo. Assuntos Militares ', ' 35 administracao publica governo assuntos militares ');
INSERT INTO indexint VALUES (34, '36', 'Assistência Social. Previdência Social. Segurança Social ', ' 36 assistencia social previdencia social seguranca social ');
INSERT INTO indexint VALUES (35, '37', 'Educação ', ' 37 educacao ');
INSERT INTO indexint VALUES (36, '38', 'Metrologia. Pesos e Medidas ', ' 38 metrologia pesos e medidas ');
INSERT INTO indexint VALUES (37, '39', 'Etnologia. Etnografia. Costumes. Modas. Tradições. Folclore ', ' 39 etnologia etnografia costumes modas tradicoes folclore ');
INSERT INTO indexint VALUES (38, '4', 'Classe vaga ', ' 4 classe vaga ');
INSERT INTO indexint VALUES (39, '5', 'Matemática e Ciências Naturais ', ' 50 matematica e ciencias naturais ');
INSERT INTO indexint VALUES (40, '50', 'Generalidades sobre as Ciências Puras ', ' 50 generalidades sobre as ciencias puras ');
INSERT INTO indexint VALUES (41, '51', 'Matemática ', ' 51 matematica ');
INSERT INTO indexint VALUES (42, '52', 'Astronomia. Astrofísica. Pesquisa Espacial. Geodesia ', ' 52 astronomia astrofisica pesquisa espacial geodesia ');
INSERT INTO indexint VALUES (43, '53', 'Física ', ' 53 fisica ');
INSERT INTO indexint VALUES (44, '54', 'Química. Mineralogia ', ' 54 quimica mineralogia ');
INSERT INTO indexint VALUES (45, '55', 'Ciências da Terra. Geologia. Meteorologia ', ' 55 ciencias da terra geologia meteorologia ');
INSERT INTO indexint VALUES (46, '56', 'Paleontologia ', ' 56 paleontologia ');
INSERT INTO indexint VALUES (47, '57', 'Biologia. Antropologia ', ' 57 biologia antropologia ');
INSERT INTO indexint VALUES (48, '58', 'Botânica ', ' 58 botanica ');
INSERT INTO indexint VALUES (49, '59', 'Zoologia ', ' 59 zoologia ');
INSERT INTO indexint VALUES (50, '6', 'Ciências Aplicadas. Medicina. Tecnologia ', ' 6 ciencias aplicadas medicina tecnologia ');
INSERT INTO indexint VALUES (51, '61', 'Ciências Médicas ', ' 61 ciencias medicas ');
INSERT INTO indexint VALUES (52, '62', 'Engenharia. Tecnologia em Geral ', ' 62 engenharia tecnologia em geral ');
INSERT INTO indexint VALUES (53, '63', 'Agricultura. Silvicultura. Agronomia. Zootecnia ', ' 63 agricultura silvicultura agronomia zootecnia ');
INSERT INTO indexint VALUES (54, '64', 'Ciência Doméstica. Economia Doméstica ', ' 64 ciencia domestica economia domestica ');
INSERT INTO indexint VALUES (55, '65', 'Organização e Administração da Indústria, do Comércio e dos Transportes ', ' 65 organizacao e administracao da industria do comercio e dos transportes ');
INSERT INTO indexint VALUES (56, '66', 'Indústria Química. Tecnologia Química ', ' 66 industria quimica tecnologia quimica ');
INSERT INTO indexint VALUES (57, '67', 'Indústrias e Ofícios Diversos ', ' 67 industrias e oficios diversos ');
INSERT INTO indexint VALUES (58, '68', 'Indústrias, Artes e Ofícios de Artigos Acabados ', ' 68 industrias artes e oficios de artigos acabados ');
INSERT INTO indexint VALUES (59, '69', 'Engenharia Civil e Estruturas em Geral. Infra-estruturas. Fundações. Construção de Túneis e de Pontes. Superestruturas ', ' 69 engenharia civil e estruturas em geral infra-estruturas fundacoes construcao de tuneis e de pontes superestruturas ');
INSERT INTO indexint VALUES (60, '7', 'Arte. Belas-artes. Recreação. Diversões. Desportos ', ' 7 arte belas-artes recreacao diversoes desportos ');
INSERT INTO indexint VALUES (61, '70', 'Generalidades ', ' 70 generalidadest ');
INSERT INTO indexint VALUES (61, '71', 'Planeamento Regional e Urbano. Paisagens, Jardins, etc ', ' 71 planeamento regional e urbano paisagens jardins etc ');
INSERT INTO indexint VALUES (62, '72', 'Arquitectura ', ' 72 arquitectura ');
INSERT INTO indexint VALUES (63, '73', 'Artes Plásticas. Escultura. Numismática ', ' 73 artes plasticas escultura numismatica ');
INSERT INTO indexint VALUES (64, '74', 'Desenho. Artes Industriais ', ' 74 desenho artes industriais ');
INSERT INTO indexint VALUES (65, '75', 'Pintura ', ' 75 pintura ');
INSERT INTO indexint VALUES (66, '76', 'Artes Gráficas ', ' 76 artes graficas ');
INSERT INTO indexint VALUES (67, '77', 'Fotografia e Cinema ', ' 77 fotografia e cinema ');
INSERT INTO indexint VALUES (68, '78', 'Música ', ' 78 musica ');
INSERT INTO indexint VALUES (69, '79', 'Entretenimento. Lazer. Jogos. Desportos ', ' 79 entretenimento lazer jogos desportos ');
INSERT INTO indexint VALUES (70, '8', 'Linguagem. Linguística. Literatura ', ' 8 linguagem linguistica literatura ');
INSERT INTO indexint VALUES (71, '80', 'Linguística. Filologia. Línguas ', ' 80 linguistica filologia linguas ');
INSERT INTO indexint VALUES (72, '81', 'vaga ', ' 81 vaga ');
INSERT INTO indexint VALUES (73, '82', 'Literatura em Língua Inglesa ', ' 82 literatura em lingua inglesa ');
INSERT INTO indexint VALUES (74, '83', 'Literatura Alemã/Escandinava/Holandesa ', ' 83 literatura alema escandinava holandesa ');
INSERT INTO indexint VALUES (75, '84', 'Literatura Francesa ', ' 84 literatura francesa ');
INSERT INTO indexint VALUES (76, '85', 'Literatura Italiana ', ' 85 literatura italiana ');
INSERT INTO indexint VALUES (77, '86', 'Literatura Espanhola/Portuguesa ', ' 86 literatura espanhola portuguesa ');
INSERT INTO indexint VALUES (78, '87', 'Literatura Clássica (Latim e Grego) ', ' 87 literatura classica latim e grego ');
INSERT INTO indexint VALUES (79, '88', 'Literatura Eslava ', ' 88 literatura eslava ');
INSERT INTO indexint VALUES (80, '89', 'Literatura em outras Línguas ', ' 89 literatura em outras linguas ');
INSERT INTO indexint VALUES (81, '9', 'Geografia. Biografia. História ', ' 9 geografia biografia historia ');
INSERT INTO indexint VALUES (82, '90', 'Arqueologia. Antiguidades ', ' 90 arqueologia antiguidades ');
INSERT INTO indexint VALUES (83, '91', 'Geografia, Exploração da Terra e Viagens ', ' 91 geografia exploracao da terra e viagens ');
INSERT INTO indexint VALUES (84, '929', 'Biografias ', ' 929 biografias ');
INSERT INTO indexint VALUES (85, '93', 'História ', ' 93 historia ');
INSERT INTO indexint VALUES (86, '94', 'História Medieval e Moderna em Geral. História da Europa ', ' 94 historia medieval e moderna em geral historia da europa ');
INSERT INTO indexint VALUES (87, '95', 'História da Ásia ', ' 95 historia da asia ');
INSERT INTO indexint VALUES (88, '96', 'História da África ', ' 96 historia da africa ');
INSERT INTO indexint VALUES (89, '97', 'História da América do Norte e Central ', ' 97 historia da america do norte e central ');
INSERT INTO indexint VALUES (90, '98', 'História da América do Sul ', ' 98 historia da america do sul ');
INSERT INTO indexint VALUES (91, '99', 'História da Oceânia, dos Territórios Árcticos e da Antárctida ', ' 99 historia da oceania dos territorios arcticos e da antarctida ');

