truncate analysis;
truncate authors;
truncate bulletins;
truncate caddie_content;
truncate collections;
truncate empr;
truncate empr_custom;
truncate empr_custom_lists;
truncate empr_custom_values;
truncate empr_groupe;
truncate error_log ;
truncate etagere ;
truncate etagere_caddie ;
truncate exemplaires;
truncate expl_custom ;
truncate expl_custom_lists ;
truncate expl_custom_values ;
truncate explnum ;
truncate groupe;
truncate import_marc ;
truncate notices;
truncate notices_categories ;
truncate notices_custom ;
truncate notices_custom_lists ;
truncate notices_custom_values ;
truncate notices_langues;
truncate pret;
truncate pret_archive ;
truncate publishers;
truncate quotas ;
truncate resa;
truncate resa_ranger ;
truncate responsability;
truncate sauv_log ;
truncate series;
truncate sub_collections;
truncate z_notices ;
truncate z_query ;
