-- +-------------------------------------------------+
-- © 2002-2004 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
-- +-------------------------------------------------+
-- $Id: indexint_100.sql,v 1.4 2006/03/11 04:18:24 touraine37 Exp $
-- 
-- Contenu de la table `indexint`
-- 

INSERT INTO indexint VALUES (1, '000', 'Information Communication', ' 000 information communication ');
INSERT INTO indexint VALUES (2, '010', 'Bibliographies Catalogues', ' 010 bibliographies catalogues ');
INSERT INTO indexint VALUES (3, '020', 'Bibliothèques - et lecture, documentation', ' 020 bibliotheques lecture documentation ');
INSERT INTO indexint VALUES (4, '030', 'Encyclopédies générales', ' 030 encyclopedies generales ');
INSERT INTO indexint VALUES (5, '040', 'X', ' 040 x ');
INSERT INTO indexint VALUES (6, '050', 'Périodiques généraux - annuaires', ' 050 periodiques generaux annuaires ');
INSERT INTO indexint VALUES (7, '060', 'Organisations générales - congrès', ' 060 organisations generales congres ');
INSERT INTO indexint VALUES (8, '070', 'Presse Edition', ' 070 presse edition ');
INSERT INTO indexint VALUES (9, '080', 'Recueils - mélanges, discours', ' 080 recueils melanges discours ');
INSERT INTO indexint VALUES (10, '090', 'Manuscrits Livres rares', ' 090 manuscrits livres rares ');
INSERT INTO indexint VALUES (11, '100', 'Philosophie', ' 100 philosophie ');
INSERT INTO indexint VALUES (12, '110', 'Métaphysique', ' 110 metaphysique ');
INSERT INTO indexint VALUES (13, '120', 'Connaissance', ' 120 connaissance ');
INSERT INTO indexint VALUES (14, '130', 'Parapsychologie - astrologie, graphologie', ' 130 parapsychologie astrologie graphologie ');
INSERT INTO indexint VALUES (15, '140', 'Systèmes philosophiques', ' 140 systemes philosophiques ');
INSERT INTO indexint VALUES (16, '150', 'Psychologie', ' 150 psychologie ');
INSERT INTO indexint VALUES (17, '160', 'Logique', ' 160 logique ');
INSERT INTO indexint VALUES (18, '170', 'Morale - ethique', ' 170 morale ethique ');
INSERT INTO indexint VALUES (19, '180', 'Philosophes anciens - et orientaux', ' 180 philosophes anciens orientaux ');
INSERT INTO indexint VALUES (20, '190', 'Philosophes modernes - (XVIe S. à nos jours)', ' 190 philosophes modernes xvie s nos jours ');
INSERT INTO indexint VALUES (21, '200', 'Religion', ' 200 religion ');
INSERT INTO indexint VALUES (22, '210', 'Religion naturelle', ' 210 religion naturelle ');
INSERT INTO indexint VALUES (23, '220', 'Bible Evangiles', ' 220 bible evangiles ');
INSERT INTO indexint VALUES (24, '230', 'Théologie doctrinale chrétienne - (dogme)', ' 230 theologie doctrinale chretienne dogme ');
INSERT INTO indexint VALUES (25, '240', 'Théologie spirituelle - vie religieuse', ' 240 theologie spirituelle vie religieuse ');
INSERT INTO indexint VALUES (26, '250', 'Théologie pastorale', ' 250 theologie pastorale ');
INSERT INTO indexint VALUES (27, '260', 'L''Eglise chrétienne et la société', ' 260 eglise chretienne societe ');
INSERT INTO indexint VALUES (28, '270', 'Histoire de l''Eglise chrétienne', ' 270 histoire eglise chretienne ');
INSERT INTO indexint VALUES (29, '280', 'Autres confessions chrétiennes', ' 280 autres confessions chretiennes ');
INSERT INTO indexint VALUES (30, '290', 'Autres religions et mythologies', ' 290 autres religions mythologies ');
INSERT INTO indexint VALUES (31, '300', 'Sciences sociales', ' 300 sciences sociales ');
INSERT INTO indexint VALUES (32, '310', 'Statistiques', ' 310 statistiques ');
INSERT INTO indexint VALUES (33, '320', 'Politique - l''Etat', ' 320 politique etat ');
INSERT INTO indexint VALUES (34, '330', 'Economie - finances, production, consommation', ' 330 economie finances production consommation ');
INSERT INTO indexint VALUES (35, '340', 'Droit - justice', ' 340 droit justice ');
INSERT INTO indexint VALUES (36, '350', 'Administration de l''Etat', ' 350 administration etat ');
INSERT INTO indexint VALUES (37, '360', 'Aide Assistance Secours', ' 360 aide assistance secours ');
INSERT INTO indexint VALUES (38, '370', 'Education - enseignement', ' 370 education enseignement ');
INSERT INTO indexint VALUES (39, '380', 'Commerce Transports Communication', ' 380 commerce transports communication ');
INSERT INTO indexint VALUES (40, '390', 'Costumes et folklore', ' 390 costumes folklore ');
INSERT INTO indexint VALUES (41, '400', 'Langage', ' 400 langage ');
INSERT INTO indexint VALUES (42, '410', 'Linguistique', ' 410 linguistique ');
INSERT INTO indexint VALUES (43, '420', 'Langue anglaise', ' 420 langue anglaise ');
INSERT INTO indexint VALUES (44, '430', 'Langue allemande', ' 430 langue allemande ');
INSERT INTO indexint VALUES (45, '440', 'Langue française - (dictionnaires, grammaire)', ' 440 langue francaise dictionnaires grammaire ');
INSERT INTO indexint VALUES (46, '450', 'Langue italienne', ' 450 langue italienne ');
INSERT INTO indexint VALUES (47, '460', 'Langue espagnole et portugaise', ' 460 langue espagnole portugaise ');
INSERT INTO indexint VALUES (48, '470', 'Langue latine', ' 470 langue latine ');
INSERT INTO indexint VALUES (49, '480', 'Langue grecque', ' 480 langue grecque ');
INSERT INTO indexint VALUES (50, '490', 'Autres langues - russe, arabe, …', ' 490 autres langues russe arabe ');
INSERT INTO indexint VALUES (51, '500', 'Sciences', ' 500 sciences ');
INSERT INTO indexint VALUES (52, '510', 'Mathématiques', ' 510 mathematiques ');
INSERT INTO indexint VALUES (53, '520', 'Astronomie', ' 520 astronomie ');
INSERT INTO indexint VALUES (54, '530', 'Physique', ' 530 physique ');
INSERT INTO indexint VALUES (55, '540', 'Chimie - minéralogie', ' 540 chimie mineralogie ');
INSERT INTO indexint VALUES (56, '550', 'Sciences de la Terre - géologie, météorologie', ' 550 sciences terre geologie meteorologie ');
INSERT INTO indexint VALUES (57, '560', 'Paléontologie - (les fossiles)', ' 560 paleontologie fossiles ');
INSERT INTO indexint VALUES (58, '570', 'Sciences de la vie - biologie, génétique', ' 570 sciences vie biologie genetique ');
INSERT INTO indexint VALUES (59, '580', 'Botanique - (les plantes)', ' 580 botanique plantes ');
INSERT INTO indexint VALUES (60, '590', 'Zoologie - (les animaux)', ' 590 zoologie animaux ');
INSERT INTO indexint VALUES (61, '600', 'Techniques', ' 600 techniques ');
INSERT INTO indexint VALUES (62, '610', 'Médecine - hygiène, santé', ' 610 medecine hygiene sante ');
INSERT INTO indexint VALUES (63, '620', 'Techniques industrielles - mécanique, électricité, radio, énergie…', ' 620 techniques industrielles mecanique electricite radio energie ');
INSERT INTO indexint VALUES (64, '630', 'Agriculture - forêt, élevage, pêche', ' 630 agriculture foret elevage peche ');
INSERT INTO indexint VALUES (65, '640', 'Arts ménagers - cuisine, coutûre, soins de beauté', ' 640 arts menagers cuisine couture soins beaute ');
INSERT INTO indexint VALUES (66, '650', 'Entreprise - travail de bureaux, vente, publicité', ' 650 entreprise travail bureaux vente publicite ');
INSERT INTO indexint VALUES (67, '660', 'Industries chimiques et alimentaires', ' 660 industries chimiques alimentaires ');
INSERT INTO indexint VALUES (68, '670', 'Fabrications industrielles - métallurgie, bois, textile', ' 670 fabrications industrielles metallurgie bois textile ');
INSERT INTO indexint VALUES (69, '680', 'Articles manufacturés', ' 680 articles manufactures ');
INSERT INTO indexint VALUES (70, '690', 'Bâtiment - construction', ' 690 batiment construction ');
INSERT INTO indexint VALUES (71, '700', 'Arts et loisirs', ' 700 arts loisirs ');
INSERT INTO indexint VALUES (72, '710', 'Urbanisme - art du paysage', ' 710 urbanisme art paysage ');
INSERT INTO indexint VALUES (73, '720', 'Architecture', ' 720 architecture ');
INSERT INTO indexint VALUES (74, '730', 'Sculpture', ' 730 sculpture ');
INSERT INTO indexint VALUES (75, '740', 'Dessin - arts décoratifs', ' 740 dessin arts decoratifs ');
INSERT INTO indexint VALUES (76, '750', 'Peinture', ' 750 peinture ');
INSERT INTO indexint VALUES (77, '760', 'Arts graphiques - graphisme', ' 760 arts graphiques graphisme ');
INSERT INTO indexint VALUES (78, '770', 'Photographie', ' 770 photographie ');
INSERT INTO indexint VALUES (79, '780', 'Musique', ' 780 musique ');
INSERT INTO indexint VALUES (80, '790', 'Loisirs - spectacles, jeux, sports', ' 790 loisirs spectacles jeux sports ');
INSERT INTO indexint VALUES (81, '800', 'Littérature', ' 800 litterature ');
INSERT INTO indexint VALUES (82, '810', 'Littérature américaine', ' 810 litterature americaine ');
INSERT INTO indexint VALUES (83, '820', 'Littérature anglaise', ' 820 litterature anglaise ');
INSERT INTO indexint VALUES (84, '830', 'Littérature allemande', ' 830 litterature allemande ');
INSERT INTO indexint VALUES (85, '840', 'Littérature française', ' 840 litterature francaise ');
INSERT INTO indexint VALUES (86, '850', 'Littérature italienne', ' 850 litterature italienne ');
INSERT INTO indexint VALUES (87, '860', 'Littérature espagnole et portugaise', ' 860 litterature espagnole portugaise ');
INSERT INTO indexint VALUES (88, '870', 'Littérature latine', ' 870 litterature latine ');
INSERT INTO indexint VALUES (89, '880', 'Littérature grecque', ' 880 litterature grecque ');
INSERT INTO indexint VALUES (90, '890', 'Autres littératures', ' 890 autres litteratures ');
INSERT INTO indexint VALUES (91, '900', 'Histoire géographie', ' 900 histoire geographie ');
INSERT INTO indexint VALUES (92, '910', 'Géographie - voyages', ' 910 geographie voyages ');
INSERT INTO indexint VALUES (93, '920', 'Biographies - vie d''un personnage, généalogie', ' 920 biographies vie personnage genealogie ');
INSERT INTO indexint VALUES (94, '930', 'Histoire ancienne', ' 930 histoire ancienne ');
INSERT INTO indexint VALUES (95, '940', 'Histoire de l''Europe', ' 940 histoire europe ');
INSERT INTO indexint VALUES (96, '950', 'Histoire de l''Asie', ' 950 histoire asie ');
INSERT INTO indexint VALUES (97, '960', 'Histoire de l''Afrique', ' 960 histoire afrique ');
INSERT INTO indexint VALUES (98, '970', 'Histoire de l''Amérique du Nord', ' 970 histoire amerique nord ');
INSERT INTO indexint VALUES (99, '980', 'Histoire de l''Amérique du Sud', ' 980 histoire amerique sud ');
INSERT INTO indexint VALUES (100, '990', 'Histoire de l''Océanie', ' 990 histoire oceanie ');
        