-- +-------------------------------------------------+
-- © 2002-2004 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
-- +-------------------------------------------------+
-- $Id: indexint_small_en.sql,v 1.4 2006/03/11 04:18:25 touraine37 Exp $
-- 
-- Contenu de la table `indexint`
-- 

INSERT INTO indexint VALUES (1, '000', 'Generalities', ' 000 generalities ');
INSERT INTO indexint VALUES (2, '010', 'Bibliography ', ' 010 bibliography ');
INSERT INTO indexint VALUES (3, '020', 'Library Science ', ' 020 library science ');
INSERT INTO indexint VALUES (4, '030', 'Encyclopedias ', ' 030 encyclopedias ');
INSERT INTO indexint VALUES (5, '040', 'Unassigned ', ' 040 unassigned ');
INSERT INTO indexint VALUES (6, '050', 'Magazines ', ' 050 magazines ');
INSERT INTO indexint VALUES (7, '060', 'Organizations, museums ', ' 060 organizations museums ');
INSERT INTO indexint VALUES (8, '070', 'Journalism ', ' 070 journalism ');
INSERT INTO indexint VALUES (9, '080', 'General collections ', ' 080 general collections ');
INSERT INTO indexint VALUES (10, '090', 'Manuscripts, rare books ', ' 090 manuscripts rare books ');
INSERT INTO indexint VALUES (11, '100', 'Philosophy ', ' 100 philosophy ');
INSERT INTO indexint VALUES (12, '110', 'Metaphysics ', ' 110 metaphysics ');
INSERT INTO indexint VALUES (13, '120', 'Epistemology ', ' 120 epistemology ');
INSERT INTO indexint VALUES (14, '130', 'Paranormal Phenomena ', ' 130 paranormal phenomena ');
INSERT INTO indexint VALUES (15, '140', 'Specific philosophies ', ' 140 specific philosophies ');
INSERT INTO indexint VALUES (16, '150', 'Psychology ', ' 150 psychology ');
INSERT INTO indexint VALUES (17, '160', 'Logic ', ' 160 logic ');
INSERT INTO indexint VALUES (18, '170', 'Ethics ', ' 170 ethics ');
INSERT INTO indexint VALUES (19, '180', 'Ancient philosophy ', ' 180 ancient philosophy ');
INSERT INTO indexint VALUES (20, '190', 'Modern philosophy ', ' 190 modern philosophy ');
INSERT INTO indexint VALUES (21, '200', 'Religion ', ' 200 religion ');
INSERT INTO indexint VALUES (22, '210', 'Natural theology ', ' 210 natural theology ');
INSERT INTO indexint VALUES (23, '220', 'Bible ', ' 220 bible ');
INSERT INTO indexint VALUES (24, '230', 'Christian theology ', ' 230 christian theology ');
INSERT INTO indexint VALUES (25, '240', 'Christian moral theology ', ' 240 christian moral theology ');
INSERT INTO indexint VALUES (26, '250', 'Christian orders ', ' 250 christian orders ');
INSERT INTO indexint VALUES (27, '260', 'Christian social theology ', ' 260 christian social theology ');
INSERT INTO indexint VALUES (28, '270', 'Christian Church History ', ' 270 christian church history ');
INSERT INTO indexint VALUES (29, '280', 'Christian denominations ', ' 280 christian denominations ');
INSERT INTO indexint VALUES (30, '290', 'Other religions ', ' 290 other religions ');
INSERT INTO indexint VALUES (31, '300', 'Social Science ', ' 300 social science ');
INSERT INTO indexint VALUES (32, '310', 'General statistics ', ' 310 general statistics ');
INSERT INTO indexint VALUES (33, '320', 'Political science ', ' 320 political science ');
INSERT INTO indexint VALUES (34, '330', 'Economics ', ' 330 economics ');
INSERT INTO indexint VALUES (35, '340', 'Law ', ' 340 law ');
INSERT INTO indexint VALUES (36, '350', 'Public administration ', ' 350 public administration ');
INSERT INTO indexint VALUES (37, '360', 'Social services ', ' 360 social services ');
INSERT INTO indexint VALUES (38, '370', 'Education ', ' 370 education ');
INSERT INTO indexint VALUES (39, '380', 'Commerce, transport ', ' 380 commerce transport ');
INSERT INTO indexint VALUES (40, '390', 'Customs, folklore ', ' 390 customs folklore ');
INSERT INTO indexint VALUES (41, '400', 'Language ', ' 400 language ');
INSERT INTO indexint VALUES (42, '410', 'Linguistics ', ' 410 linguistics ');
INSERT INTO indexint VALUES (43, '420', 'English ', ' 420 english ');
INSERT INTO indexint VALUES (44, '430', 'German ', ' 430 german ');
INSERT INTO indexint VALUES (45, '440', 'French ', ' 440 french ');
INSERT INTO indexint VALUES (46, '450', 'Italian, Romanian ', ' 450 italian romanian ');
INSERT INTO indexint VALUES (47, '460', 'Spanish, Portuguese ', ' 460 spanish portuguese ');
INSERT INTO indexint VALUES (48, '470', 'Latin ', ' 470 latin ');
INSERT INTO indexint VALUES (49, '480', 'Classical Greek ', ' 480 classical greek ');
INSERT INTO indexint VALUES (50, '490', 'Other languages ', ' 490 other languages ');
INSERT INTO indexint VALUES (51, '500', 'Science ', ' 500 science ');
INSERT INTO indexint VALUES (52, '510', 'Mathematics ', ' 510 mathematics ');
INSERT INTO indexint VALUES (53, '520', 'Astronomy ', ' 520 astronomy ');
INSERT INTO indexint VALUES (54, '530', 'Physics ', ' 530 physics ');
INSERT INTO indexint VALUES (55, '540', 'Chemistry ', ' 540 chemistry ');
INSERT INTO indexint VALUES (56, '550', 'Earth sciences ', ' 550 earth sciences ');
INSERT INTO indexint VALUES (57, '560', 'Paleontology ', ' 560 paleontology ');
INSERT INTO indexint VALUES (58, '570', 'Life sciences ', ' 570 life sciences ');
INSERT INTO indexint VALUES (59, '580', 'Botany ', ' 580 botany ');
INSERT INTO indexint VALUES (60, '590', 'Zoology ', ' 590 zoology ');
INSERT INTO indexint VALUES (61, '600', 'Technology ', ' 600 technology ');
INSERT INTO indexint VALUES (62, '610', 'Medicine ', ' 610 medicine ');
INSERT INTO indexint VALUES (63, '620', 'Engineering ', ' 620 engineering ');
INSERT INTO indexint VALUES (64, '630', 'Agriculture ', ' 630 agriculture ');
INSERT INTO indexint VALUES (65, '640', 'Home economics ', ' 640 home economics ');
INSERT INTO indexint VALUES (66, '650', 'Management ', ' 650 management ');
INSERT INTO indexint VALUES (67, '660', 'Chemical engineering ', ' 660 chemical engineering ');
INSERT INTO indexint VALUES (68, '670', 'Manufacturing ', ' 670 manufacturing ');
INSERT INTO indexint VALUES (69, '680', 'Specific industries ', ' 680 specific industries ');
INSERT INTO indexint VALUES (70, '690', 'Buildings ', ' 690 buildings ');
INSERT INTO indexint VALUES (71, '700', 'Arts, Entertainment ', ' 700 arts entertainment ');
INSERT INTO indexint VALUES (72, '710', 'Civic & landscape art ', ' 710 civic landscape art ');
INSERT INTO indexint VALUES (73, '720', 'Architecture ', ' 720 architecture ');
INSERT INTO indexint VALUES (74, '730', 'Plastic arts, Sculpture ', ' 730 plastic arts sculpture ');
INSERT INTO indexint VALUES (75, '740', 'Drawing, decorative arts ', ' 740 drawing decorative arts ');
INSERT INTO indexint VALUES (76, '750', 'Painting ', ' 750 painting ');
INSERT INTO indexint VALUES (77, '760', 'Graphic arts, Printmaking ', ' 760 graphic arts printmaking ');
INSERT INTO indexint VALUES (78, '770', 'Photography ', ' 770 photography ');
INSERT INTO indexint VALUES (79, '780', 'Music ', ' 780 music ');
INSERT INTO indexint VALUES (80, '790', 'Recreation, performing arts ', ' 790 recreation performing arts ');
INSERT INTO indexint VALUES (81, '800', 'Literature ', ' 800 literature ');
INSERT INTO indexint VALUES (82, '810', 'American ', ' 810 american ');
INSERT INTO indexint VALUES (83, '820', 'English ', ' 820 english ');
INSERT INTO indexint VALUES (84, '830', 'German ', ' 830 german ');
INSERT INTO indexint VALUES (85, '840', 'French ', ' 840 french ');
INSERT INTO indexint VALUES (86, '850', 'Italian, Romanian ', ' 850 italian romanian ');
INSERT INTO indexint VALUES (87, '860', 'Spanish, Portuguese ', ' 860 spanish portuguese ');
INSERT INTO indexint VALUES (88, '870', 'Latin ', ' 870 latin ');
INSERT INTO indexint VALUES (89, '880', 'Classical Greek ', ' 880 classical greek ');
INSERT INTO indexint VALUES (90, '890', 'Other literatures ', ' 890 other literatures ');
INSERT INTO indexint VALUES (91, '900', 'Geography & History ', ' 900 geography history ');
INSERT INTO indexint VALUES (92, '910', 'Geography & travel ', ' 910 geography travel ');
INSERT INTO indexint VALUES (93, '920', 'Biography, genealogy ', ' 920 biography genealogy ');
INSERT INTO indexint VALUES (94, '930', 'History of ancient world ', ' 930 history of ancient world ');
INSERT INTO indexint VALUES (95, '940', 'History of Europe ', ' 940 history of europe ');
INSERT INTO indexint VALUES (96, '950', 'History of Asia ', ' 950 history of asia ');
INSERT INTO indexint VALUES (97, '960', 'History of Africa ', ' 960 history of africa ');
INSERT INTO indexint VALUES (98, '970', 'History of North America ', ' 970 history of north america ');
INSERT INTO indexint VALUES (99, '980', 'History of South America ', ' 980 history of south america ');
INSERT INTO indexint VALUES (100, '990', 'History of other areas ', ' 990 history of other areas ');
        